# Generated by Django 4.2.16 on 2024-10-03 16:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('altitude', models.FloatField(blank=True, null=True)),
                ('values', models.JSONField()),
                ('dateTime', models.DateTimeField()),
                ('accuracy', models.FloatField(blank=True, help_text='Accuracy of the measurement', null=True)),
                ('unit', models.CharField(blank=True, help_text='Unit of measurement (e.g., Sieverts)', max_length=20, null=True)),
                ('notes', models.TextField(blank=True, help_text='Optional notes or comments on the measurement', null=True)),
                ('weather', models.JSONField(blank=True, help_text='Weather conditions during the measurement (if available)', null=True)),
                ('measurement_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.device')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Measurement',
                'verbose_name_plural': 'Measurements',
                'ordering': ['-dateTime'],
            },
        ),
    ]
