# Generated by Django 4.2.16 on 2024-10-03 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='hash',
            field=models.CharField(blank=True, max_length=64, unique=True),
        ),
    ]
