# Generated by Django 4.2.16 on 2024-10-03 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_alter_device_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicemodel',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='devicemodel',
            name='technology',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
