# Generated by Django 4.2.16 on 2024-10-03 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_devicemodel_description_devicemodel_technology'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicemodel',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='device_pictures/'),
        ),
    ]
