# Generated by Django 4.2.16 on 2024-10-07 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_devicemodel_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicemodel',
            name='validatedByOpenRed',
            field=models.BooleanField(default=False),
        ),
    ]
